version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mqtt-mongodb
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - mqtt-mongo-data:/data/db
    networks:
      - mqtt-network

  mosquitto:
    image: iegomez/mosquitto-go-auth:latest
    container_name: mqtt-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./src/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
    networks:
      - mqtt-network

volumes:
  mqtt-mongo-data:

networks:
  mqtt-network:
    driver: bridge